version: "{build}"

os: Visual Studio 2015

clone_folder: c:\gopath\src\github.com\git-time-metric\gtm

skip_branch_with_pr: true

environment:
  GOPATH: c:\gopath
  PROJ_DIR: /c/gopath/src/github.com/git-time-metric/gtm

install:
  - go env
  - go version

build_script:
  - c:\msys64\usr\bin\bash -lc "cd ${PROJ_DIR} && make git2go-install"
  - c:\msys64\usr\bin\bash -lc "/c/gopath/src/github.com/git-time-metric/gtm/script/appveyor-build.sh"

artifacts:
  - path: gtm.$(appveyor_repo_tag_name).windows.tar.gz
    name: gtm.zip

  - path: 'gtm.developer-build-*.windows.tar.gz'
    name: gtm-developer.tar.gz

deploy:
  description: ''
  provider: GitHub
  auth_token:
    secure: O47of1Osqbk2qkk1Vn228XXF/YDwev5j5YHyNPzEPJR1pxuqwPaqlvsFDVUYQoiu
  artifact: gtm.zip
  force_update: true
  on:
    appveyor_repo_tag: true
