name: build-linux
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1' # The Go version to download (if necessary) and use.
      - run: go version
      - name: Install dependecies
        run: |
          sudo apt-get install libgit2-dev libssh2-1-dev libssl-dev cmake
          make git2go
          go get github.com/mattn/goveralls
      - name: Build
        run: |
          go get -d ./...
          $HOME/gopath/bin/goveralls -v -flags=--tags=static -service=travis-ci